import { defineConfig } from "vite-plus";
import { devtools } from "@tanstack/devtools-vite";

import { tanstackStart } from "@tanstack/react-start/plugin/vite";

import viteReact from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { nitro } from "nitro/vite";

// Under Vitest we don't want the SSR server adapter (nitro) or the
// TanStack Start server plugin — they break the test environment and the
// unit/component tests don't need them.
const isTest = process.env.VITEST === "true";

// Pick the Nitro preset at build time. Set `NITRO_PRESET=cloudflare-module`
// (or use the `build:cf` script) to produce a Workers bundle; otherwise we
// fall back to the default Node preset which is what `vp dev` expects.
const nitroPreset = process.env.NITRO_PRESET;

const appPlugins = isTest
  ? [viteReact()]
  : [
      devtools(),
      nitro({
        ...(nitroPreset
          ? {
              preset: nitroPreset,
              cloudflare: {
                wrangler: {
                  name: "homefolio",
                  compatibility_date: "2025-03-15",
                  observability: { enabled: true },
                },
              },
            }
          : {}),
        rollupConfig: { external: [/^@sentry\//] },
      }),
      tailwindcss(),
      tanstackStart(),
      viteReact(),
    ];

// `src/routeTree.gen.ts` is generated by the TanStack Router plugin on every
// dev/build run and owns its own formatting — exclude it from fmt/lint so
// `vp check` doesn't churn on a file we don't hand-edit.
const generatedFiles = ["src/routeTree.gen.ts"];

const config = defineConfig({
  staged: {
    // Fast pre-commit: format + lint staged files only. We deliberately
    // avoid `vp check --fix` here because its type-check phase is far too
    // slow for a commit hook (see docs/adr/0001).
    "*.{ts,tsx,js,jsx,json,css,md}": ["vp fmt --write", "vp exec oxlint --fix"],
  },
  fmt: { ignorePatterns: generatedFiles },
  // Keep the default `vp check`/`vp lint` loop FAST: oxlint only, no
  // type-aware rules. Type-aware linting + full type-checking run the
  // TypeScript checker over the whole project, which takes minutes — far
  // too slow for the inner dev loop. Run those explicitly via
  // `vp run typecheck` (and in CI) instead. Opt into type-aware lint
  // ad-hoc with `vp lint --type-aware`.
  lint: { ignorePatterns: generatedFiles },
  resolve: { tsconfigPaths: true },
  plugins: appPlugins,
  build: {
    rollupOptions: {
      external: ["cloudflare:workers"],
    },
  },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/__tests__/_setup/setup.ts"],
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
  },
});

export default config;
