/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSystemsRouteImport } from './routes/_app.systems'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppItemsRouteImport } from './routes/_app.items'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppBlueprintRouteImport } from './routes/_app.blueprint'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSystemsRoute = AppSystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppBlueprintRoute = AppBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof TemplatesRoute
  '/activities': typeof AppActivitiesRoute
  '/blueprint': typeof AppBlueprintRoute
  '/documents': typeof AppDocumentsRoute
  '/items': typeof AppItemsRoute
  '/rooms': typeof AppRoomsRoute
  '/systems': typeof AppSystemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof TemplatesRoute
  '/activities': typeof AppActivitiesRoute
  '/blueprint': typeof AppBlueprintRoute
  '/documents': typeof AppDocumentsRoute
  '/items': typeof AppItemsRoute
  '/rooms': typeof AppRoomsRoute
  '/systems': typeof AppSystemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof TemplatesRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/blueprint': typeof AppBlueprintRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/items': typeof AppItemsRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/systems': typeof AppSystemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/search'
    | '/setup'
    | '/sign-in'
    | '/templates'
    | '/activities'
    | '/blueprint'
    | '/documents'
    | '/items'
    | '/rooms'
    | '/systems'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/search'
    | '/setup'
    | '/sign-in'
    | '/templates'
    | '/activities'
    | '/blueprint'
    | '/documents'
    | '/items'
    | '/rooms'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/search'
    | '/setup'
    | '/sign-in'
    | '/templates'
    | '/_app/activities'
    | '/_app/blueprint'
    | '/_app/documents'
    | '/_app/items'
    | '/_app/rooms'
    | '/_app/systems'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/systems': {
      id: '/_app/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof AppSystemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blueprint': {
      id: '/_app/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof AppBlueprintRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppBlueprintRoute: typeof AppBlueprintRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppItemsRoute: typeof AppItemsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSystemsRoute: typeof AppSystemsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppBlueprintRoute: AppBlueprintRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppItemsRoute: AppItemsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSystemsRoute: AppSystemsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
